MVCMusicStoreApplication/MVCMusicStoreApplication/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCMusicStoreApplication.Models;

namespace MVCMusicStoreApplication.Controllers
{
    public class ShoppingCartController : Controller
    {
        MVCMusicStoreDB db = new MVCMusicStoreDB();
        // GET: ShoppingCart
        public ActionResult Index()
        {
            ShoppingCart cart = ShoppingCart.GetCart(this.HttpContext);

            ShoppingCartViewModel vm = new ShoppingCartViewModel() {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetCartTotal()
            };

            return View(vm);
        }

        public ActionResult AddToCart(int id) {
            ShoppingCart cart = ShoppingCart.GetCart(this.HttpContext);
            cart.AddToCart(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult RemoveFromCart(int id) {
            ShoppingCart cart = ShoppingCart.GetCart(this.HttpContext);

            Album album = db.Carts.SingleOrDefault(c => c.RecordId == id).AlbumSelected;

            int newItemCount = cart.RemoveFromCart(id);

            ShoppingCartRemoveViewModel vm = new ShoppingCartRemoveViewModel() {
                DeleteId = id,
                CartTotal = cart.GetCartTotal(),
                ItemCount = newItemCount,
                Message = $@"Your item: {album.Title} has been removed from the cart."
            };

            return Json(vm);
        }
    }
}

MVCMusicStoreApplication/MVCMusicStoreApplication/Controllers/StoreFrontController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCMusicStoreApplication.Controllers
{
    public class StoreFrontController : Controller
    {

        MVCMusicStoreDB db = new MVCMusicStoreDB();

        // GET: StoreFront
        public ActionResult Index(int id){
            var genreAlbums = db.Albums.Where(a => a.GenreId == id).ToList();
            return View("Index", genreAlbums);
        }

        public ActionResult Browse() {
            var genres = db.Genres.ToList().OrderBy(g => g.Name);
            return View("Browse", genres);
        }

        public ActionResult Details(int id) {
            var album = db.Albums.FirstOrDefault(a => a.AlbumId == id);
            return View("Details", album);
        }

    }
}

MVCMusicStoreApplication/MVCMusicStoreApplication/Views/StoreFront/Browse.cshtml
@model IEnumerable<MVCMusicStoreApplication.Models.Genre>

@{
    ViewBag.Title = "Browse";
}

<div>
    <h2>Browse by Genre</h2>
    <ul style="list-style-type:none;">
        @foreach (var title in Model) {
            <li>@Html.ActionLink(title.Name, "Index", new { id = title.GenreId })</li>
        }

    </ul>
</div>

MVCMusicStoreApplication/MVCMusicStoreApplication/Views/StoreFront/Details.cshtml
@model MVCMusicStoreApplication.Models.Album

<h2>Album Details</h2>

<div>
    <h4>@Model.Title</h4>
    <img src="@Model.AlbumArtUrl" />
    <h5>Artist: @Model.Artist.Name</h5>
    <h5>Price: $@Model.Price</h5>
</div>
<button class="btn-sm btn-success">
   @Html.ActionLink("Add to Cart", "AddToCart", "ShoppingCart", new { id = Model.AlbumId }, "")
</button>

MVCMusicStoreApplication/MVCMusicStoreApplication/Views/StoreFront/Index.cshtml
@model IEnumerable<MVCMusicStoreApplication.Models.Album>


<div>
    <h2>Here are the list of albums:</h2>
</div>
@if (Model.Any()) {
    <ul style="list-style-type:none;">
        @foreach (var album in Model) {
        <li>@Html.ActionLink(album.Title + " - " + album.Artist.Name, "Details", new { id = album.AlbumId })</li> 
        }
    </ul>
} else {
    <h4>Sorry, there are no albums for the selected genre.</h4>
}

@Html.ActionLink("Back to Browse", "Browse", "StoreFront")