EventFinalProject/EventFinalProject/Models/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EventFinalProject.Models {
    public class Event {
        public virtual int EventId { get; set; }
        public virtual int CategoryId { get; set; }
        public virtual int OrganizerId { get; set; }
        [Required]
        [MaxLength(50, ErrorMessage = "Oops...title cannot exceed 50 characters, try again.")]
        public virtual string Title { get; set; }
        [MaxLength(500, ErrorMessage = "Uh oh...description cannot exceed 150 characters, try again.")]
        public virtual string Description { get; set; }
        [Required]
        public virtual string AddressLine1 { get; set; }
        public virtual string AddressLine2 { get; set; }
        [Required]
        public virtual string City { get; set; }
        [Required]
        public virtual string State { get; set; }
        [Required]
        public virtual int Zipcode { get; set; }
        [Required]
        public virtual DateTime StartDateTime { get; set; }
        [Required]
        public virtual DateTime EndDateTime { get; set; }
        public virtual Category Category { get; set; }
        public virtual Organizer Organizer { get; set; }
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Oopsie daisy...Maximum number of tickets must be greater than zero.")]
        public virtual int MaxTickets { get; set; }
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Oh no...Number of available tickets must be greater than zero.")]
        public virtual int AvailableTickets { get; set; }
        public virtual decimal Price { get; set; }
    }
}

EventFinalProject/EventFinalProject/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EventFinalProject.Models;

namespace EventFinalProject.Controllers
{
    public class CategoryController : Controller
    {
        private EventFinalProjectDB db = new EventFinalProjectDB();

        // GET: Category
        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        // GET: Category/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Category/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoryId,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Category/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Category/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoryId,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Category/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EventFinalProject/EventFinalProject/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EventFinalProject.Models;

namespace EventFinalProject.Controllers
{
    public class EventController : Controller
    {
        private EventFinalProjectDB db = new EventFinalProjectDB();

        public ActionResult Index()
        {
            IQueryable<Event> events = db.Events.Include(e => e.Category).Include(e => e.Organizer);
            return View("Index",events.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event myEvent = db.Events.Find(id);
            if (myEvent == null)
            {
                return HttpNotFound();
            }
            return View(myEvent);
        }

        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name");
            ViewBag.OrganizerId = new SelectList(db.Organizers, "OrganizerId", "LastName");
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EventId,CategoryId,Category,Organizer,OrganizerId,EventIcon,Title,Description,AddressLine1,AddressLine2,City,State,Zipcode,StartDateTime,EndDateTime,MaxTickets,AvailableTickets,Price")] Event myEvent)
        {
            if (ModelState.IsValid)
            {
                db.Events.Add(myEvent);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name", myEvent.CategoryId);
            ViewBag.OrganizerId = new SelectList(db.Organizers, "OrganizerId", "FirstName", myEvent.OrganizerId);
            return View(myEvent);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event oneEvent = db.Events.Find(id);
            if (oneEvent == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name", oneEvent.CategoryId);
            ViewBag.OrganizerId = new SelectList(db.Organizers, "OrganizerId", "FirstName", oneEvent.OrganizerId);
            return View(oneEvent);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EventId,CategoryId,OrganizerId,EventIcon,Title,Description,AddressLine1,AddressLine2,City,State,Zipcode,StartDateTime,EndDateTime,MaxTickets,AvailableTickets,Price")] Event oneEvent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(oneEvent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name", oneEvent.CategoryId);
            ViewBag.OrganizerId = new SelectList(db.Organizers, "OrganizerId", "FirstName", oneEvent.OrganizerId);
            return View(oneEvent);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event oneEvent = db.Events.Find(id);
            if (oneEvent == null)
            {
                return HttpNotFound();
            }
            return View(oneEvent);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event oneEvent = db.Events.Find(id);
            db.Events.Remove(oneEvent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult EventSearchByName(string keyword) {
            var events = db.Events.Where(e => e.Category.Name.Contains(keyword) || e.Title.Contains(keyword)).ToList();
            return PartialView("_EventSearch", events.OrderBy(e => e.Title));
        }

        public ActionResult EventSearchByLocation(string keyword) {
            var events = db.Events.Where(e => e.City.Contains(keyword) || e.State.Contains(keyword)).ToList();
            return PartialView("_EventSearch", events.OrderBy(e => e.Title));
        }

        public ActionResult LastMinuteDeals() {
            var allEvents = db.Events.ToList();
            List<Event> lastMinuteDeals = new List<Event>();
            foreach(var oneEvent in allEvents) {
                if(DateTime.Now < oneEvent.StartDateTime && DateTime.Now.AddDays(2) > oneEvent.StartDateTime) {
                    lastMinuteDeals.Add(oneEvent);
                }
            }

            return PartialView("_LastMinuteDeals", lastMinuteDeals.OrderBy(e => e.Title));
        }
    }
}

EventFinalProject/EventFinalProject/Controllers/OrderItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EventFinalProject.Models;

namespace EventFinalProject.Controllers {
    public class OrderItemsController : Controller {
        private EventFinalProjectDB db = new EventFinalProjectDB();

        // GET: OrderItems
        public ActionResult Index(OrderItem item) {
            Order newOrder = new Order();
            Random rng = new Random();
            newOrder.OrderId = rng.Next(9999);
            newOrder.OrderItems.Add(item);
            newOrder.OrderTotal = 0;
            newOrder.UserId = 1;
            return View(newOrder);
        }

        // GET: OrderItems/Details/5
        public ActionResult Details(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderItem orderItem = db.OrderItems.Find(id);
            if (orderItem == null) {
                return HttpNotFound();
            }
            return View(orderItem);
        }

        // GET: OrderItems/Create
        public ActionResult Create() {
            return View();
        }

        // POST: OrderItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrderItemId,OrderId,EventId,Quantity")] OrderItem orderItem) {
            if (ModelState.IsValid) {
                db.OrderItems.Add(orderItem);
                var order = new Order();
                order.OrderItems.Add(orderItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(orderItem);
        }

        // GET: OrderItems/Edit/5
        public ActionResult Edit(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderItem orderItem = db.OrderItems.Find(id);
            if (orderItem == null) {
                return HttpNotFound();
            }
            return View(orderItem);
        }

        // POST: OrderItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrderItemId,OrderId,EventId,Quantity")] OrderItem orderItem) {
            if (ModelState.IsValid) {
                db.Entry(orderItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(orderItem);
        }

        // GET: OrderItems/Delete/5
        public ActionResult Delete(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderItem orderItem = db.OrderItems.Find(id);
            if (orderItem == null) {
                return HttpNotFound();
            }
            return View(orderItem);
        }

        // POST: OrderItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) {
            OrderItem orderItem = db.OrderItems.Find(id);
            db.OrderItems.Remove(orderItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing) {
            if (disposing) {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


    }
}

EventFinalProject/EventFinalProject/Views/Event/Create.cshtml
@model EventFinalProject.Models.Event

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h3>Organize an Event</h3>
    <hr />

    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.StartDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartDateTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StartDateTime, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.EndDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndDateTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EndDateTime, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AddressLine1, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AddressLine1, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AddressLine1, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AddressLine2, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AddressLine2, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AddressLine2, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Zipcode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Zipcode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Zipcode, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.CategoryId, "Event Type", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" id="createEventType">
            @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })  
            @Html.ActionLink("Add Event Type", "Create", "Category", "", htmlAttributes: new { @class = "btn btn-success" })
            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Organizer.FirstName, "Organizer First Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Organizer.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Organizer.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Organizer.LastName, "Organizer Last Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Organizer.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Organizer.LastName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Organizer.PhoneNumber, "Organizer Phone #", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Organizer.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Organizer.PhoneNumber, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.MaxTickets, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaxTickets, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaxTickets, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AvailableTickets, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AvailableTickets, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AvailableTickets, "", new { @class = "text-danger" })
        </div>
    </div>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EventFinalProject/EventFinalProject/Views/Event/Details.cshtml
@model EventFinalProject.Models.Event

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Organizer.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Organizer.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressLine1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressLine1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressLine2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressLine2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zipcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zipcode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxTickets)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxTickets)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AvailableTickets)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AvailableTickets)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Register", "AddToOrder", "OrderItems", "", new { id = Model.EventId }) |
    @Html.ActionLink("Edit", "Edit", new { id = Model.EventId }) |
    @Html.ActionLink("Delete", "Delete", new { id = Model.EventId })
</p>

EventFinalProject/EventFinalProject/Views/Event/Index.cshtml
<div class="jumbotron">
    <h1>EventFULL</h1>
    <p class="lead">Looking for something fun to do? Search for an activity and make life more EventFULL. Want to organize an event? We can help! Click "Organize an Event" to get started.</p>
</div>

<div class="panel panel-default" id="mainPageDiv">
    <div class="panel-heading">Find an Event</div>
    <div class="panel-body" id="mainSection">
        @using (Ajax.BeginForm("EventSearchByName", "Event", new AjaxOptions {
            InsertionMode = InsertionMode.Replace,
            HttpMethod = "GET",
            OnFailure = "searchFailed",
            LoadingElementId = "ajax-loader",
            UpdateTargetId = "searchResults"
        })) {
            <div id="input1">
                <input type="text" name="keyword" id="searchInput" />
                <input type="submit" class="btn btn-default" value="Event or Event Type" />
                <img id="ajax-loader"
                     src="@Url.Content("~/Content/ajax-loader.gif")"
                     height="20" width="20" style="display:none" />
            </div>
        }
        @using (Ajax.BeginForm("EventSearchByLocation", "Event", new AjaxOptions {
            InsertionMode = InsertionMode.Replace,
            HttpMethod = "GET",
            OnFailure = "searchFailed",
            LoadingElementId = "ajax-loader",
            UpdateTargetId = "searchResults"
        })) {
            <div id="input2">
                <input type="text" name="keyword" />
                <input type="submit" class="btn btn-default" value="City or State" />
                <img id="ajax-loader"
                     src="@Url.Content("~/Content/ajax-loader.gif")"
                     height="20" width="20" style="display:none" />
            </div>
        }
        <div>
            @using (Ajax.BeginForm("LastMinuteDeals", "Event", new AjaxOptions {
                InsertionMode = InsertionMode.Replace,
                HttpMethod = "GET",
                OnFailure = "searchFailed",
                LoadingElementId = "ajax-loader",
                UpdateTargetId = "searchResults"
            })) {
                <input type="submit" class="btn btn-primary" value="Last Minute Deals" />
                <img id="ajax-loader"
                     src="@Url.Content("~/Content/ajax-loader.gif")"
                     height="20" width="20" style="display:none" />
            }
        </div>
    </div>
    <div id="searchResults"></div>
</div>
@section Scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/ProjectJS/EventProjectScripts.js"></script>
}

EventFinalProject/EventFinalProject/Views/Event/_EventSearch.cshtml
@model IEnumerable<EventFinalProject.Models.Event>

<div>
        <table id="searchTable" width="1200">
            <thead>
                <tr>
                    <th>Event Title</th>
                    <th>Start Date & Time</th>
                    <th>City</th>
                    <th>State</th>
                </tr>
            </thead>
           
           
            <tbody>
                @if (Model.Count() == 0) {
                    <tr>
                        <td>Your search returned no results.</td>
                    </tr>
                }

                @foreach (var oneEvent in Model) {
                    <tr>
                        <td>@Html.ActionLink(oneEvent.Title, "Details", "Event", new { id = oneEvent.EventId}, null)</td>
                        <td>@oneEvent.StartDateTime.ToShortDateString() - @oneEvent.StartDateTime.ToShortTimeString()</td>
                        <td>@oneEvent.City</td>
                        <td>@oneEvent.State</td>
                    </tr>
                }
            </tbody>
        </table>
</div>

EventFinalProject/EventFinalProject/Views/Event/_LastMinuteDeals.cshtml
@model IEnumerable<EventFinalProject.Models.Event>

<div>
    <table id="searchTable" width="1200">
        <thead>
            <tr>
                <th>Event Title</th>
                <th>Start Date & Time</th>
                <th>City</th>
                <th>State</th>
            </tr>
        </thead>


        <tbody>
            @if (Model.Count() == 0) {
                <tr>
                    <td>Currently, there are no last minute deals.</td>
                </tr>
            }

            @foreach (var oneEvent in Model) {
                <tr>
                    <td width="25%">@Html.ActionLink(oneEvent.Title, "Details", "Event", new { id = oneEvent.EventId }, null)</td>
                    <td width="25%">@oneEvent.StartDateTime.ToShortDateString() - @oneEvent.StartDateTime.ToShortTimeString()</td>
                    <td width="20%">@oneEvent.City</td>
                    <td width="20%">@oneEvent.State</td>
                </tr>
            }
        </tbody>
    </table>
</div>